import{a as i}from"./assets/vendor-1b0a9daf.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const b=document.querySelector(".js-open-menu"),p=document.querySelector(".header-backdrop");b.addEventListener("click",y);p.addEventListener("click",y);function y(){p.classList.toggle("is-hidden")}let u="filter=Muscles",l=1;const q=document.querySelector(".exercises-list-btn"),h=document.querySelector('button[data-action="filter=Muscles"]'),L=document.querySelector('button[data-action="filter=Body parts"]'),S=document.querySelector('button[data-action="filter=Equipment"]');q.addEventListener("click",v);function v(o){h.classList.remove("active"),L.classList.remove("active"),S.classList.remove("active"),o.target.classList.add("active"),u=o.target.dataset.action,l=1,f(u,l)}const d=document.querySelector(".js-exercises-countpage"),g=document.querySelector(".quote-text"),m=document.querySelector(".quote-author");async function x(){i.defaults.baseURL="https://energyflow.b.goit.study/api/quote";const o=new Date,s=o.getFullYear()+String(o.getMonth())+o.getDate();let n={};if(localStorage.getItem("quotation")&&(n=JSON.parse(localStorage.getItem("quotation"))),!localStorage.getItem("quotation")||s!==n.date){const a=await i.get();try{g.textContent=a.data.quote,m.textContent=a.data.author;const e={date:s,quote:a.data.quote,author:a.data.author};localStorage.setItem("quotation",JSON.stringify(e))}catch(e){alert(e.message)}}else g.textContent=n.quote,m.textContent=n.author}x();const E=document.querySelector(".js-exercises-list");f();async function f(o="filter=Muscles",s=1){i.defaults.baseURL="https://energyflow.b.goit.study/api/";const n="filters",a={page:s,limit:8},e=await i.get(`${n}?${o}`,{params:a});try{const t=e.data.totalPages;if(t>1){let r="";for(let c=1;c<=t;c+=1)c===s?r+=`<button data-action=${c} class="js-exercises-countpage-btn active " type="button">${c}</button>`:r+=`
          <button data-action=${c} class="js-exercises-countpage-btn " type="button">${c}</button>
        `;d.innerHTML=r,d.addEventListener("click",k)}M(e.data.results)}catch(t){alert(t.message)}}function k(o){for(const s of d.children)s.classList.remove("active");o.target.classList.add("active"),l=Number(o.target.dataset.action),f(u,l)}function M(o){const s=o.reduce((n,{name:a,filter:e,imgUrl:t})=>n+`
      <li class="exercises-item">
        <a class="exercises-link" href="">
            <img
            class="exercises-image"
            src="${t}"
            alt="${a}"
            />
            <div class="div-position">
                <p class="exercises-filter">${e}</p>
                <p class="exercises-name">${a}</p>
            </div>
         </a>
       </li>`,"");E.innerHTML=s}
//# sourceMappingURL=commonHelpers.js.map
